name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Restore NuGet
      uses: actions/setup-nuget@v1
    
    - run: nuget restore ../../src/CloudAwesome.Xrm.Core/CloudAwesome.Xrm.Core.sln
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Test
      run: dotnet test --no-build --verbosity normal
